server:
  port: 9002


spring:
  application:
    name: pm-service-owner

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  # mysql数据库连接
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/heima-estate?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123

  profiles:
    active: dev

  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8
  redis:
    port: 6379
    connect-timeout: 5000
    database: 0
    password: 123456


mybatis-plus:

  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


  global-config:
    db-config:
      id-type: auto

gitee:
  oauth:
    clientid: 068b619f6c8711924ed0494bbf936cd5c8ed8b87999b2bffa614d9ec15298f68
    clientsecret: 366bb54937ec6d729d2dc2048dc2c71a2182818c3d60b15f4893f32733a4811b
    callback: http://localhost:8080/#/pages/my/my
