server:
  port: 9007
#  servlet:
#    session:
#      timeout: 30m


spring:
  application:
    name: pm-auth
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

#  session:
#    store-type: redis


  profiles:
    active: dev

  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8



mybatis-plus:

  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


  global-config:
    db-config:
      id-type: auto



